### ISSUE TITLE
After r16 merge I am having issues building..

### ISSUE THREAD

**Issue by saikat0511** [DerpLab/platform_system_vold#2]
[ 53% 5259/9900] //system/vold:libvold clang++ FsCrypt.cpp
FAILED: /home/saikat/derp_ten/out/soong/.intermediates/system/vold/libvold/android_arm64_armv8-a_cortex-a53_core_static/obj/system/vold/FsCrypt.o
PWD=/proc/self/cwd prebuilts/clang/host/linux-x86/clang-r353983c/bin/clang++ -c -Isystem/vold  -Werror=implicit-function-declaration -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer
-arith -no-canonical-prefixes -DNDEBUG -UDEBUG -fno-exceptions -Wno-multichar -O2 -g -fno-strict-aliasing -fdebug-prefix-map=/proc/self/cwd= -D__compiler_offsetof=__builtin_offsetof -faddrsig -Wimplicit-f
allthrough -Werror=int-conversion -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -fcolor-diagnostics -Wno-zero-as-null-pointer-constant -Wno-sign-compare -Wno-defaulted-func
tion-deleted -Wno-inconsistent-missing-override -ffunction-sections -fdata-sections -fno-short-enums -funwind-tables -fstack-protector-strong -Wa,--noexecstack -D_FORTIFY_SOURCE=2 -Wstrict-aliasing=2 -Wer
ror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=date-time -Werror=format-security -nostdlibinc -march=armv8-a -mcpu=cortex-a53 -Ivendor/qcom/opensource/cryptfs_hw -
I/home/saikat/derp_ten/out/soong/.intermediates/system/apex/apexd/sysprop/libcom.android.sysprop.apex/android_arm64_armv8-a_cortex-a53_core_static/gen/sysprop/include -Iexternal/avb -Ibootable/recovery/bo
otloader_message/include -Isystem/extras/libfec/include -Isystem/core/libcrypto_utils/include -Iexternal/fec -Isystem/core/fs_mgr/libfs_avb/include -Isystem/core/fs_mgr/include_fstab -Isystem/core/fs_mgr/
include -Isystem/core/logwrapper/include -Isystem/core/fs_mgr/libdm/include -Isystem/core/fs_mgr/liblp/include -Iexternal/scrypt/lib/crypto -Isystem/extras/squashfs_utils -I/home/saikat/derp_ten/out/soong
/.intermediates/system/vold/libvold_binder/android_arm64_armv8-a_cortex-a53_core_static/gen/aidl -Iexternal/libcxx/include -Iexternal/libcxxabi/include -Isystem/libhidl/base/include -Isystem/core/libcutil
s/include -Isystem/core/libprocessgroup/include -Isystem/core/libutils/include -Isystem/core/libbacktrace/include -Isystem/core/liblog/include -Isystem/core/libsystem/include -Isystem/libhidl/transport/in
clude -I/home/saikat/derp_ten/out/soong/.intermediates/system/libhidl/transport/manager/1.0/android.hidl.manager@1.0_genc++_headers/gen -I/home/saikat/derp_ten/out/soong/.intermediates/system/libhidl/tran
sport/manager/1.1/android.hidl.manager@1.1_genc++_headers/gen -I/home/saikat/derp_ten/out/soong/.intermediates/system/libhidl/transport/manager/1.2/android.hidl.manager@1.2_genc++_headers/gen -I/home/saik
at/derp_ten/out/soong/.intermediates/system/libhidl/transport/base/1.0/android.hidl.base@1.0_genc++_headers/gen -Isystem/libhwbinder/include -Isystem/core/base/include -I/home/saikat/derp_ten/out/soong/.i
ntermediates/hardware/interfaces/keymaster/3.0/android.hardware.keymaster@3.0_genc++_headers/gen -I/home/saikat/derp_ten/out/soong/.intermediates/hardware/interfaces/keymaster/4.0/android.hardware.keymast
er@4.0_genc++_headers/gen -I/home/saikat/derp_ten/out/soong/.intermediates/hardware/interfaces/boot/1.0/android.hardware.boot@1.0_genc++_headers/gen -Iframeworks/native/libs/binder/include -I/home/saikat/
derp_ten/out/soong/.intermediates/frameworks/native/libs/binder/libbinder/android_arm64_armv8-a_cortex-a53_core_shared/gen/aidl -Iexternal/boringssl/src/include -Isystem/core/libdiskconfig/include -Isyste
m/extras/ext4_utils/include -Isystem/extras/f2fs_utils -Isystem/extras/libfscrypt/include -Ihardware/libhardware/include -Isystem/media/audio/include -Isystem/bt/types -Ihardware/libhardware_legacy/includ
e -Ihardware/interfaces/keymaster/4.0/support/include -Isystem/core/libkeyutils/include -Iexternal/selinux/libselinux/include -Isystem/core/libsysutils/include -I/home/saikat/derp_ten/out/soong/.intermedi
ates/hardware/interfaces/health/storage/1.0/android.hardware.health.storage@1.0_genc++_headers/gen -Ibionic/libc/include -D__LIBC_API__=10000 -D__LIBM_API__=10000 -D__LIBDL_API__=10000 -Isystem/core/inclu
de -Isystem/media/audio/include -Ihardware/libhardware/include -Ihardware/libhardware_legacy/include -Ihardware/ril/include -Iframeworks/native/include -Iframeworks/native/opengl/include -Iframeworks/av/i
nclude -isystem bionic/libc/include -isystem bionic/libc/kernel/uapi -isystem bionic/libc/kernel/uapi/asm-arm64 -isystem bionic/libc/kernel/android/scsi -isystem bionic/libc/kernel/android/uapi -Ilibnativ
ehelper/include_jni -Wall -Werror -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-variable -DCONFIG_HW_DISK_ENCRYPTION -target aarch64-linux-android -Bprebuilts/gcc/linux-x86/aar
ch64/aarch64-linux-android-4.9/aarch64-linux-android/bin -DANDROID_STRICT -fPIC -D_USING_LIBCXX -std=gnu++17 -Wsign-promo -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wno-thread-safety-negative -Wno-gnu-in
clude-next -fvisibility-inlines-hidden -D__ANDROID_DEBUGGABLE__ -fno-rtti  -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=address-of-temporary -Werror=return-type -Wno-tautological-consta
nt-compare -Wno-tautological-type-limit-compare -Wno-tautological-unsigned-enum-zero-compare -Wno-tautological-unsigned-zero-compare -Wno-c++98-compat-extra-semi -Wno-return-std-move-in-c++11 -MD -MF /hom
e/saikat/derp_ten/out/soong/.intermediates/system/vold/libvold/android_arm64_armv8-a_cortex-a53_core_static/obj/system/vold/FsCrypt.o.d -o /home/saikat/derp_ten/out/soong/.intermediates/system/vold/libvol
d/android_arm64_armv8-a_cortex-a53_core_static/obj/system/vold/FsCrypt.o system/vold/FsCrypt.cpp
system/vold/FsCrypt.cpp:444:64: error: use of undeclared identifier 'fscrypt_key_per_boot_ref'
    std::string per_boot_ref_filename = std::string("/data") + fscrypt_key_per_boot_ref;
                                                               ^
1 error generated.
12:41:51 ninja failed with: exit status 1

**Comment by MASTERGUY** [comment]
remove 440 to 447 line stuffs 

there was a pull request seems closed 

https://github.com/DerpLab/platform_system_vold/commit/96a074dd2c9bbeeddc9239fce6904d0a754ef836

follow this up it will fix your issues

ooh btw it is merged now you can sync your sources again to see
